#!/bin/bash
# Script to restart MariaDB on droplets.
#
# Written by agentpoyo 2019-12-27
# agentpoyo@gmail.com

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details. <http://www.gnu.org/licenses/>.


# Smaller DO droplets seem to kill off MySQL from time to time.
# This script can be scheduled to check every minute and if 
# mysqld isn't detected, restarts it.

SVC=mysql

if (( $(ps -ef | grep -v grep | grep $SVC | wc -l) > 0 ))
  then
    echo "MariaDB running, nothing to do."
  else
    /usr/bin/systemctl restart mariadb
fi
